msvc14:
    script:
        - "mkdir build"
        - "cd build"
        - "cmake -DCMAKE_BUILD_TYPE=Release -G \"Visual Studio 14 Win64\" .."
        - "cmake --build ."
    tags:
        - win10

msvc14_clang:
    script:
        - "mkdir build"
        - "cd build"
        - "cmake -DCMAKE_BUILD_TYPE=Release -G \"Visual Studio 14 Win64\" -T v140_clang_3_7 .."
        - "cmake --build ."
    tags:
        - vs2015

linux_gcc:
    script:
        - "mkdir build"
        - "cd build"
        - "CC=gcc CXX=g++ cmake -DCMAKE_BUILD_TYPE=Release .."
        - "cmake --build ."
    tags:
        - lin

linux_clang:
    script:
        - "mkdir build"
        - "cd build"
        - "CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Release .."
        - "cmake --build ."
    tags:
        - lin

mac_xcode:
    script:
        - "mkdir build"
        - "cd build"
        - "cmake -GXcode -DCMAKE_BUILD_TYPE=Release .."
        - "cmake --build ."
    tags:
        - mac
