win10:
    script:
        - "git submodule update --init"
        - "mkdir build"
        - "cd build"
        - "cmake -G \"Visual Studio 14 Win64\" .."
        - "cmake --build ."
    tags:
        - win10
