win10:
    script:
        - "mkdir build"
        - "cd build"
        - "cmake -G \"Visual Studio 14 Win64\" .."
        - "cmake --build ."
    tags:
        - win10

win7:
    script:
        - "mkdir build"
        - "cd build"
        - "cmake -G \"Visual Studio 14 Win64\" .."
        - "cmake --build ."
    tags:
        - win7

linux:
    script:
        - "mkdir build"
        - "cd build"
        - "cmake .."
        - "cmake --build ."
    tags:
        - lin

mac:
    script:
        - "mkdir build"
        - "cd build"
        - "cmake .."
        - "cmake --build ."
    tags:
        - mac
